/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.krismorte.twitterinstamigration.view;

import com.krismorte.twitterinstamigration.model.InstaAccount;
import com.krismorte.twitterinstamigration.model.InstaAccountAccess;
import com.krismorte.twitterinstamigration.model.Post;
import com.krismorte.twitterinstamigration.model.Tweet;
import com.krismorte.twitterinstamigration.model.TwitterAccount;
import com.krismorte.twitterinstamigration.model.TwitterAccountAccess;
import com.towel.el.annotation.AnnotationResolver;
import com.towel.swing.table.ObjectTableModel;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import org.brunocvcunha.instagram4j.Instagram4j;
import org.brunocvcunha.instagram4j.requests.InstagramUserFeedRequest;
import org.brunocvcunha.instagram4j.requests.payload.InstagramFeedItem;
import org.brunocvcunha.instagram4j.requests.payload.InstagramFeedResult;
import twitter4j.MediaEntity;
import twitter4j.Status;
import twitter4j.Twitter;

/**
 *
 * @author krisnamourtscf
 */
public class MainScreen extends javax.swing.JFrame {

    private final String DIR_IMAGE = "stream";
    private AnnotationResolver resolverTweet = new AnnotationResolver(Tweet.class);
    private ObjectTableModel<Tweet> tableModelTweet = new ObjectTableModel<Tweet>(resolverTweet, "image,text,userName");
    private AnnotationResolver resolverInsta = new AnnotationResolver(Post.class);
    private ObjectTableModel<Post> tableModelPost = new ObjectTableModel<Post>(resolverInsta, "image,text,userName");
    private List<Tweet> tweets = new ArrayList<>();
    private List<Post> posts = new ArrayList<>();
    private JTable tableTweet;
    private JTable tablePost;

    private InstaAccount instaAccount;
    private TwitterAccount twitterAccount;
    private Twitter twitter;
    private Instagram4j instagram;

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        setutTest();
        /*Tweet t = new Tweet();
        t.setText("teste");
        t.setUserName("kris");
        tweets.add(t);
        showTweetTable(tweets);
        Post t = new Post();
        t.setText("teste");
        t.setUserName("kris");
        posts.add(t);
        showPostTable(posts);*/
    }

    private void setutTest() {
        System.setProperty("http.proxyHost", "172.31.3.254");
        System.setProperty("http.proxyPort", "3128");
        InstaAccountAccess instaAccess = new InstaAccountAccess();
        instaAccess.setUserName("mauaudog");
        instaAccess.setPassword("025935@KM");
        instaAccount = new InstaAccount();
        instaAccount.setAccountAccess(instaAccess);
        TwitterAccountAccess twitterAccess = new TwitterAccountAccess();
        twitterAccess.setAccessToken("704982112626208768-1YI46mKJELm3LNx9Dn16RN6QhLj0N5B");
        twitterAccess.setAccessTokenSecret("kmSgQRjk3iPVha6JgfnyVQ68Kk2YAhO8olwBzWa89485h");
        twitterAccess.setConsumerKey("mO4icXUBevZ6ORLBY3kpja42A");
        twitterAccess.setConsumerSecret("h7IwOOAFsTR9fCOnLawG4TNhOpZqYs9otW6tNFYioGadDFGkmS");
        twitterAccount = new TwitterAccount();
        twitterAccount.setAccountAccess(twitterAccess);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        panelFeed = new javax.swing.JPanel();
        btnTweet = new javax.swing.JButton();
        btnInsta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("accounts");

        panelFeed.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelFeedLayout = new javax.swing.GroupLayout(panelFeed);
        panelFeed.setLayout(panelFeedLayout);
        panelFeedLayout.setHorizontalGroup(
            panelFeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelFeedLayout.setVerticalGroup(
            panelFeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );

        btnTweet.setText("search tweet");
        btnTweet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTweetActionPerformed(evt);
            }
        });

        btnInsta.setText("search insta");
        btnInsta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelFeed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnTweet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInsta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 321, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnTweet)
                    .addComponent(btnInsta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFeed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTweetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTweetActionPerformed
        try {
            twitter = (Twitter) twitterAccount.getAccountAccess().getConnection();
            for (Status status : twitter.timelines().getHomeTimeline()) {
                List<String> arquivos = new ArrayList<>();
                if (status.getMediaEntities().length > 0) {
                    arquivos = download(DIR_IMAGE, status);
                }
                tweets.add(new Tweet(status, arquivos));
            }
            showTweetTable(tweets);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnTweetActionPerformed

    private void btnInstaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstaActionPerformed
        try {
            instagram = (Instagram4j) instaAccount.getAccountAccess().getConnection();
            InstagramFeedResult result = instagram.sendRequest(new InstagramUserFeedRequest(1761990178));

            /*for (InstagramFeedItem item : result.getItems()) {
                posts.add(new Post(item));
            }*/
            showPostTable(posts);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnInstaActionPerformed

    private List<String> download(String directoryName, Status status) {

        MediaEntity[] medias = status.getMediaEntities();
        System.out.println("Total video " + medias.length);
        List<String> path = new ArrayList<>();
        if (medias.length > 0) {
            File directory = createDirectoryIfNotExists(directoryName);
            for (MediaEntity m : medias) {
                try {
                    URL url = new URL(m.getMediaURL());
                    if (m.getVideoVariants().length > 0) {//is video
                        for (MediaEntity.Variant v : m.getVideoVariants()) {
                            url = new URL(v.getUrl());
                        }
                    }

                    for (MediaEntity.Variant v : m.getVideoVariants()) {
                        System.out.println("V: " + v.getUrl());
                        System.out.println("V: " + v.getContentType());
                    }

                    //URL url = new URL(m.getMediaURL());
                    InputStream in = new BufferedInputStream(url.openStream());
                    ByteArrayOutputStream out = new ByteArrayOutputStream();
                    byte[] buf = new byte[1024];
                    int n = 0;
                    while (-1 != (n = in.read(buf))) {
                        out.write(buf, 0, n);
                    }
                    out.close();
                    in.close();
                    byte[] response = out.toByteArray();
                    String pathImage = directory.getAbsolutePath() + "\\" + m.getId() + "." + getExtension(m.getType());
                    path.add(pathImage);
                    FileOutputStream fos = new FileOutputStream(pathImage);
                    fos.write(response);
                    fos.close();
                } catch (Exception ex) {
                    System.err.println("Não consegui baixar a imagem");
                    ex.printStackTrace();
                }
            }
        }
        return path;
    }

    private File createDirectoryIfNotExists(String directory) {
        File file = new File(directory);
        if (file.exists()) {
            for (File child : file.listFiles()) {
                child.delete();
            }
            return file;
        } else {
            file.mkdir();
            return file;
        }
    }

    private String getExtension(String type) {
        if (type.equals("photo")) {
            return "jpg";
        } else if (type.equals("video")) {
            return "mp4";
        } else if (type.equals("animated_gif")) {
            return "gif";
        } else {
            return "err";
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsta;
    private javax.swing.JButton btnTweet;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel panelFeed;
    // End of variables declaration//GEN-END:variables

    private void showTweetTable(List<Tweet> tweets) {
        tableModelTweet.setData(tweets);
        tableTweet = new JTable(tableModelTweet);
        tableTweet.setRowHeight(80);
        JScrollPane pane = new JScrollPane();
        pane.setViewportView(tableTweet);
        pane.setVisible(true);
        tableTweet.setPreferredSize(new Dimension(400, 200));
        tableTweet.setVisible(true);
        tableTweet.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e); //To change body of generated methods, choose Tools | Templates.
                if (e.getClickCount() > 1) {
                    new TweetView(tableModelTweet.getValue(tableTweet.getSelectedRow()));
                }
            }

        });

        panelFeed.removeAll();
        panelFeed.setLayout(new GridLayout(1, 1));
        panelFeed.add(pane);
        panelFeed.validate();
    }

    private void showPostTable(List<Post> posts) {

        tableModelPost.setData(posts);
        tablePost = new JTable(tableModelPost);
        tablePost.setRowHeight(80);
        JScrollPane pane = new JScrollPane();
        pane.setViewportView(tablePost);
        pane.setVisible(true);
        tablePost.setPreferredSize(new Dimension(400, 400));
        tablePost.setVisible(true);

        panelFeed.removeAll();
        panelFeed.setLayout(new GridLayout(1, 1));
        panelFeed.add(pane);
        panelFeed.validate();
    }

}
